spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/colleges?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
#        url: jdbc:mysql://172.16.20.69:3306/sunshuai?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
#         password: root
        password: 123456

        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ss.data.bean
server:
  port: 8081
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
